# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7b2e831f1620969d0f133c1511cab936939ed969e30d70c5ccee76bdc711726f27aac7fda20d0af786a68266b1f9caf7fc44bb58ac7eca85e5ca2dc3d8e60a9e

test:
  secret_key_base: a835bd51d60e732cb9a5af3382d383f10f8e8bb554ddac18d652e3020536bfced4cd63d2eeb4b3ccb4ece1f4886aa0a07074e04bb866d5b4733c0f90f5ae32d5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
